### ISSUE TITLE
[BUG] nfl.import_weekly_pfr data missing for 2024 Week 1 season

### ISSUE THREAD

**Issue by Laneville** [nflverse/nfl_data_py#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.3

### Describe the bug

When running the function nfl.import_weekly_pfr('rush',[2024]), I am only seeing values for the games that took place on Thursday and Friday of Week 1. Sunday and Monday games are missing.

### Reprex

```r
import nfl_data_py as nfl
rush = nfl.import_weekly_pfr('rush', [2024])
print(rush)
```

### Expected Behavior

I would expect to see a dataframe with up-to-date per-game data sourced from players' advanced gamelog pages on pro-football-reference.com for 2024 week 1

### nflverse_sitrep

```r
na
```

**Comment by Laneville** [comment]
![image](https://github.com/user-attachments/assets/a15a661a-7d1c-4554-905d-8f0b51814599)

**Comment by zachaustin01** [comment]
+1

**Comment by rjthompson2** [comment]
+1
