### ISSUE TITLE
2024 data not available

### ISSUE THREAD

**Issue by nateb7722** [nflverse/nfl_data_py#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.2 (also tried 0.3.1)

### Describe the bug

2024 Data is currently not available. Even when typing in the html to download the parquet, 2023 is available but 2024 is not. Not sure if this is a temporary issue related to when data is updated or if there is a different problem. TIA!

### Reprex

```r
import nfl_data_py
test = nfl_data_py.import_pbp_data([2024])
```

### Expected Behavior

2024 data to be downloaded

### nflverse_sitrep

```r
NA
```

**Comment by tanho63** [comment]
See: https://github.com/nflverse/nfl_data_py/issues/99#issuecomment-2342212809

**Comment by nateb7722** [comment]
Thank you!! huge help
