### ISSUE TITLE
[BUG] PBP Participation not available for 2024

### ISSUE THREAD

**Issue by tjjerome** [nflverse/nfl_data_py#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

0.3.2

### Describe the bug

PBP participation data is missing for 2024. Causes an error when importing pbp data without the "include_participation=False" option.

### Reprex

```r
import nfl_data_py as nfl
pbp = nfl.import_pbp_data([2024])
```

### Expected Behavior

Data is imported properly

### nflverse_sitrep

```r
NA
```

**Comment by tanho63** [comment]
https://x.com/John_B_Edwards/status/1832091502895579354

**Comment by alecglen** [comment]
Adding to that context, this will be fixed so it doesn't throw an error soon (probably tomorrow). In the mean time, use the `include_participation` argument as a workaround.
