### ISSUE TITLE
[BUG] Missing PFR Week 4 Data

### ISSUE THREAD

**Issue by mawi510** [nflverse/nfl_data_py#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.3

### Describe the bug

I'm looking for some passing stats from the `import_weekly_pfr` function, but I only see the DAL/NYG game and none of the games in Week 4

### Reprex

Using the package's function

```python
import nfl_data_py as nfl

weekly_pfr = nfl.import_weekly_pfr('pass',years)

#The below only returns one game for week 4 instead of the expected 16
weekly_pfr[weekly_pfr['week'] == 4]
weekly_pfr.groupby('week')['game_id'].nunique()
```

Hitting the parquet file directly
```python
import nfl_data_py as nfl

url = "https://github.com/nflverse/nflverse-data/releases/download/pfr_advstats/advstats_week_{0}_{1}.parquet"
weekly_pfr =  pd.concat([
    pd.read_parquet(url.format('pass', yr))
    for yr in years
])
#The below only returns one game for week 4 instead of the expected 16
weekly_pfr[weekly_pfr['week'] == 4]
weekly_pfr.groupby('week')['game_id'].nunique()
```

### Expected Behavior

PFR's site has data for all 16 games from week 4, so I thought stats from all 16 games would be available

### nflverse_sitrep

```r
NA
```

**Comment by alecglen** [comment]
It seems like the basic stats were available for those games, but the [advanced stats sections](https://www.pro-football-reference.com/boxscores/202409290rav.htm#all_passing_advanced) weren't populated until today.

@mawi510 you should see the package return all 16 games now.

**Comment by mawi510** [comment]
Great, thank you for the clarification!
