### ISSUE TITLE
[BUG] NGS data has issues

### ISSUE THREAD

**Issue by jakemdaly** [nflverse/nfl_data_py#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

0.3.3

### Describe the bug

NGS data contains errors. Some of the stats for multiple weeks are compressed into a single week's entry

```python
ngs = nfl.import_ngs_data('receiving', [2023])
```

![image](https://github.com/user-attachments/assets/84069c32-12b7-468c-a126-fbb49a72a659)

### Reprex

```r
Inspect the data for Tank Dell or Rashee Rice for the 2023 season in the DF returned by

`ngs = nfl.import_ngs_data('receiving', [2023])`
```

### Expected Behavior

The data should be expanded to contain all the data from those weeks.

### nflverse_sitrep

```r
NA
```

**Comment by mrcaseb** [comment]
That's expected behavior. Week 0 is a season summary. You can confirm this by checking the related tables on the ngs website.

**Comment by jakemdaly** [comment]
Ok thanks, so then some weeks are just missing data?

**Comment by john-b-edwards** [comment]
Yes, not every player qualifies for the NGS leaderboard each week, and the NGS website doesn't provide stats on these players who don't qualify.

**Comment by jakemdaly** [comment]
Thanks for the information, I didn't know that!
