### ISSUE TITLE
[BUG] Snap count data incorrect

### ISSUE THREAD

**Issue by bendub21** [nflverse/nfl_data_py#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.3

### Describe the bug

Using Python and nfl.import_snap_counts(2023). For week 12 Lamar Jackson is listed in the 'player' column twice. One row contains what I assume is Jackson's legit snap count data and the pfr_player_id is JackLa00, the second row shows pfr_player_id for Lamar Jackson as JackLa02 and then what looks like data for a Panther's cornerback?

I haven't dug into it any further than that, since I was only looking at Lamar's stats, but thought I'd report it since this could be a data generation issue and occur elsewhere.

### Reprex

```r
years: list[int] = [2023]
snap_count_data: pd.DataFrame = nfl.import_snap_counts(years)
snap_count_data.to_csv('./snap_data.csv')
```

### Expected Behavior

I would expect a single row per player per week containing snap count related data.

### nflverse_sitrep

```r
NA
```

### Screenshots

```markdown
https://imgur.com/a/52KDlfx
```

**Comment by alecglen** [comment]
Hey @bendub21! I'd like to introduce you to [Panthers cornerback Lamar Jackson](https://en.m.wikipedia.org/wiki/Lamar_Jackson_(cornerback)) 😄

There are a number of shared-name cases like this in the history books - notably Josh Allen, Michael Thomas, and several Mike Williams's. For that reason, you should go by player ID whenever possible. If you encounter a situation where an ID isn't available, then a combination of name, team and position can get you _*most*_ of the way there.

**Comment by bendub21** [comment]
Haha well that would explain it! Thanks for enlightening me :)

And for the repo!
