### ISSUE TITLE
python-snappy issue persisting

### ISSUE THREAD

**Issue by alecglen** [nflverse/nfl_data_py#77]
Stemming from https://github.com/cooperdff/nfl_data_py/pull/69#issuecomment-1830037557.

**Comment by alecglen** [comment]
@vinostroud moving your question over here as I believe it's a slightly different problem.

A couple troubleshooting steps:

1. Run `pip3 -V`. Confirm that the path directory printed is the correct Python environment you expect to interacting with.
2. Run `pip3 show nfl-data-py`. Paste the output below.

**Comment by vinostroud** [comment]
Thank you very much for responding.

The directory looks correct. The virtual environment is running etc.

Showing below my terminal input (1st line) and terminal output (second line)


```
(nfl_data_jup_venv) ********* nfl_data_jup_venv % pip3 show nfl-data-py             

WARNING: Package(s) not found: nfl-data-py
```

**Comment by alecglen** [comment]
Could you please specify your OS and venv setup? I'd like to investigate this deeper but haven't been able to reproduce it.

**Comment by vinostroud** [comment]
Absolutely. 

--I am on MacOS Ventura 13.6.1
--Using VSCode -- Version: 1.84.2 (Universal)

Definitely not an expert in virtual environments, but my process (I think) was pretty standard:
--Navigate to local directory (a folder sitting on my desktop)
--In terminal run `python3 -m venv my_env_name`
--activate venv using `source my_env_name/bin/activate`

Then I created a kernel for the project if that might matter?

Again - no issues installing and interacting with `nfl-data-py` if I go through conda on this same computer

**Comment by alecglen** [comment]
@vinostroud sorry for the confusion. I just realized the fix you originally commented on was never released to PyPI.

I will get that released when I have time, possibly this weekend. In the meantime, please use the following command to install directly from the repository and avoid this issue.
`pip install --upgrade nfl-data-py@git+https://github.com/cooperdff/nfl_data_py`

**Comment by vinostroud** [comment]
@alecglen Thank you very much -- the direct install worked perfectly. Really appreciate the responsiveness on this.

**Comment by ccdickerson** [comment]
sorry I am new to coding but im trying to use pycharm and I put pip install nfl_data_py and this error pops up 

 ERROR: Failed building wheel for python-snappy
  Running setup.py clean for python-snappy
Failed to build python-snappy
ERROR: Could not build wheels for python-snappy, which is required to install pyproject.toml-based projects

**Comment by vinostroud** [comment]
@ccdickerson -- if you run the command alecglen provided above, it should install successfully using pycharm.

pip install --upgrade nfl-data-py@git+https://github.com/cooperdff/nfl_data_py

**Comment by ccdickerson** [comment]
thank you I should have read more!!

**Comment by pembeci** [comment]
> @vinostroud sorry for the confusion. I just realized the fix you originally commented on was never released to PyPI.
> 
> I will get that released when I have time, possibly this weekend. In the meantime, please use the following command to install directly from the repository and avoid this issue. `pip install --upgrade nfl-data-py@git+https://github.com/cooperdff/nfl_data_py`

Tried to install today and problem is still there.  So I guess PyPI release didn't happen yet. If someone finds this thread who is using `poetry`, one workaround is deleting the `python-snappy` dependency for this package from `poetry.lock` file manually.

**Comment by alecglen** [comment]
Hey all, my apologies and thanks for your patience! Version 0.3.2 containing the fix has finally been released to PyPI. You can install it with the command `pip install --force-reinstall --upgrade nfl-data-py`.

I'll be catching up on issues and adding new datasets in this repo over the next few weeks, so please don't hesitate to report any other issues you see or [nflverse datasets](https://nflreadr.nflverse.com/articles/index.html) you'd like to see prioritized!

**Comment by vinostroud** [comment]
Terrific, thank you @alecglen! in time for summer camp. Looking forward to seeing the new datasets!

**Comment by IceeCodee** [comment]
I am having the same issue. I tried the above command:
 pip install --upgrade nfl-data-py@git+https://github.com/cooperdff/nfl_data_py
I am getting error ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
Do i need to change the version of pandas I am using? I curently have 2.2.2

**Comment by alecglen** [comment]
@IceeCodee yes, nfl_data_py only supports pandas 1.X for the moment - see https://github.com/nflverse/nfl_data_py/issues/98#issuecomment-2344408893.

If you need pandas 2.X, you can bypass the requirement by downgrading temporarily, installing nfl_data_py, and then upgrading pandas. Many functions likely work fine, but there are some caveats as described in that comment.
