### ISSUE TITLE
snappy issue

### ISSUE THREAD

**Issue by ccdickerson** [nflverse/nfl_data_py#78]
sorry I am new to coding but im trying to use pycharm and I put pip install nfl_data_py and this error pops up

ERROR: Failed building wheel for python-snappy
Running setup.py clean for python-snappy
Failed to build python-snappy
ERROR: Could not build wheels for python-snappy, which is required to install pyproject.toml-based projects

**Comment by RGAlexander216** [comment]
I'm also having the same error.

**Comment by alecglen** [comment]
@RGAlexander216 please see the answer here https://github.com/cooperdff/nfl_data_py/issues/77#issuecomment-1830397207

**Comment by RGAlexander216** [comment]
That fixed it, appreciate it.
