### ISSUE TITLE
Unable to install 0.3.1 package when using PyCharm CE 2023.3.3 and Python v3.12.2

### ISSUE THREAD

**Issue by bendub21** [nflverse/nfl_data_py#84]
When attempting to install nfl-data-py for use in my code I'm getting the following output:

`Collecting nfl-data-py==0.3.1
  Using cached nfl_data_py-0.3.1-py3-none-any.whl
Requirement already satisfied: pandas>1 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from nfl-data-py==0.3.1) (2.2.1)
Collecting appdirs>1 (from nfl-data-py==0.3.1)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting fastparquet>0.5 (from nfl-data-py==0.3.1)
  Using cached fastparquet-2024.2.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting python-snappy>0.5 (from nfl-data-py==0.3.1)
  Using cached python-snappy-0.6.1.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.20.3 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from fastparquet>0.5->nfl-data-py==0.3.1) (1.26.4)
Collecting cramjam>=2.3 (from fastparquet>0.5->nfl-data-py==0.3.1)
  Using cached cramjam-2.8.1-cp312-none-win_amd64.whl.metadata (4.2 kB)
Collecting fsspec (from fastparquet>0.5->nfl-data-py==0.3.1)
  Using cached fsspec-2024.2.0-py3-none-any.whl.metadata (6.8 kB)
Collecting packaging (from fastparquet>0.5->nfl-data-py==0.3.1)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from pandas>1->nfl-data-py==0.3.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from pandas>1->nfl-data-py==0.3.1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from pandas>1->nfl-data-py==0.3.1) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\bdub2\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>1->nfl-data-py==0.3.1) (1.16.0)
Using cached fastparquet-2024.2.0-cp312-cp312-win_amd64.whl (669 kB)
Using cached cramjam-2.8.1-cp312-none-win_amd64.whl (1.6 MB)
Using cached fsspec-2024.2.0-py3-none-any.whl (170 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Building wheels for collected packages: python-snappy
  Building wheel for python-snappy (pyproject.toml): started
  Building wheel for python-snappy (pyproject.toml): finished with status 'error'
Failed to build python-snappy

  error: subprocess-exited-with-error
  
  Building wheel for python-snappy (pyproject.toml) did not run successfully.
  exit code: 1
  
  [27 lines of output]
  C:\Users\bdub2\AppData\Local\Temp\pip-build-env-hdw9tdkh\overlay\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'cffi_modules'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-312
  creating build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\hadoop_snappy.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\snappy.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\snappy_cffi.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\snappy_cffi_builder.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\snappy_formats.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\__init__.py -> build\lib.win-amd64-cpython-312\snappy
  copying src\snappy\__main__.py -> build\lib.win-amd64-cpython-312\snappy
  running build_ext
  building 'snappy._snappy' extension
  creating build\temp.win-amd64-cpython-312
  creating build\temp.win-amd64-cpython-312\Release
  creating build\temp.win-amd64-cpython-312\Release\src
  creating build\temp.win-amd64-cpython-312\Release\src\snappy
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\bdub2\AppData\Local\Programs\Python\Python312\include -IC:\Users\bdub2\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/snappy/crc32c.c /Fobuild\temp.win-amd64-cpython-312\Release\src/snappy/crc32c.obj
  crc32c.c
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\bdub2\AppData\Local\Programs\Python\Python312\include -IC:\Users\bdub2\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc/snappy/snappymodule.cc /Fobuild\temp.win-amd64-cpython-312\Release\src/snappy/snappymodule.obj
  snappymodule.cc
  src/snappy/snappymodule.cc(33): fatal error C1083: Cannot open include file: 'snappy-c.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-snappy
ERROR: Could not build wheels for python-snappy, which is required to install pyproject.toml-based projects`

I'm using PyCharm CE 2023.3.3 and Python v3.12.2.

**Comment by alecglen** [comment]
[This is fixed!](https://github.com/nflverse/nfl_data_py/issues/77#issuecomment-2263857121)
