### ISSUE TITLE
[BUG] import_schedule shows wrong week for rest

### ISSUE THREAD

**Issue by darkhark** [nflverse/nfl_data_py#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.1

### Describe the bug

If the `home_rest` and `away_rest` columns are meant to represent each team's bye weeks, they appear to default to 7. This is for week 1:
![image](https://github.com/nflverse/nfl_data_py/assets/55332998/32d47eed-558e-46c7-94f4-cb1f83e949ed)
The rest value changes depending on the week for the same teams too.

### Reprex

```r
import nfl_data_py as nfl
nfl.import_schedules([2023])[['away_team', 'home_team', 'away_rest', 'home_rest']]
```

### Expected Behavior

The values in rest week show the same bye week for the same team no matter the week.

### nflverse_sitrep

```r
NA
```

### Screenshots

```markdown
Added to description
```

### Additional context

Not urgent, but I planned on imputing values using the bye week.

**Comment by smenon02** [comment]
is there anyone working on this? If not, I can take it up

**Comment by darkhark** [comment]
> is there anyone working on this? If not, I can take it up
> 
> 

You're the first reply. Feel free to go for it!

**Comment by nateb7722** [comment]
These columns look like they represent the days of rest for each team going into that game. not the bye week. Is that not the intended use of these columns? Should I be calculating days rest differently?

**Comment by tanho63** [comment]
![image](https://github.com/user-attachments/assets/524b6a3f-814c-47ac-8dd6-31f7b8a5c232)
https://nflreadr.nflverse.com/articles/dictionary_schedules.html

this is indeed days of rest for home/away team (i.e. number of days since last game before the game date)
