### ISSUE TITLE
[BUG] UnboundLocalError: cannot access local variable 'plays' where it is not associated with a value

### ISSUE THREAD

**Issue by kazirshahria** [nflverse/nfl_data_py#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.2

### Describe the bug

When I try to import play-by-play data using Python I get an error.

### Reprex

```r
nfl.import_pbp_data([2020])
```

### Expected Behavior

It does not return the dataframe.

### nflverse_sitrep

```r
NA
```

**Comment by alecglen** [comment]
Hi @kazirshahria, what is the error you're getting?

**Comment by kazirshahria** [comment]
Hi @alecglen.
![Screenshot 2024-08-16 174041](https://github.com/user-attachments/assets/94a75062-cd64-4618-b585-bad0772b90b7)

**Comment by alecglen** [comment]
That one I am aware of and have fixed in the upcoming version 0.3.3 release. Please run the following command in your terminal to install it, restart your notebook kernel, and let me know if that fixes it.

`pip install --force-reinstall nfl-data-py@git+https://github.com/nflverse/nfl_data_py.git@v0.3.3`

**Comment by kazirshahria** [comment]
It works! Thank you so much.
