### ISSUE TITLE
[BUG] AttributeError when calling import_pbp_data function due to undefined 'Error' in exception handling.

### ISSUE THREAD

**Issue by ivy113** [nflverse/nfl_data_py#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

This is not a data-related issue.

### What version of the package do you have?

0.3.2

### Describe the bug

While attempting to use the import_pbp_data function in nfl_data_py, an AttributeError is raised due to the usage of an undefined 'Error' in the exception handling code. This causes the program to fail when trying to catch an exception.

### Reprex

```r
import nfl_data_py as nfl
pbp_data = nfl.import_pbp_data(years=[2023])
```

### Expected Behavior

nfl.import_pbp_data should return a dataframe of the data for the year specified.

### nflverse_sitrep

```r
NA
```

### Additional context

AttributeError                            Traceback (most recent call last)
File ~/miniforge3/envs/sports/lib/python3.10/site-packages/nfl_data_py/__init__.py:140, in import_pbp_data(years, columns, include_participation, downcast, cache, alt_path, thread_requests)
    139 try:
--> 140     data = pandas.read_parquet(path, columns=columns if columns else None, engine='auto')
    142     raw = pandas.DataFrame(data)
...
--> 153 except Error as e:
    154     print(e)
    155     print('Data not available for ' + str(year))

NameError: name 'Error' is not defined

**Comment by alecglen** [comment]
Hey @ivy113, thanks for the report! I actually have this fixed already in the upcoming [0.3.3 release](https://github.com/nflverse/nfl_data_py/pull/92). Sorry for the confusion; I'm still figuring out the best way to manage releases in here.

In the meantime until that is merged, you can install it directly from the release branch by using the command below:
```
pip install --force-reinstall nfl-data-py@git+https://github.com/nflverse/nfl_data_py.git@v0.3.3
```

**Comment by ivy113** [comment]
Thanks for letting me know! The pull request I filed was in regards to this, so please toss as it is no longer relevant.

**Comment by Laneville** [comment]
Sorry to re-open this. But I'm seeing this similar error happening when I try to pull for 2024 (this year). I'm looking to get some pbp stats for week 1 but it's giving me the same "NameError: name 'Error' is not defined"
