### ISSUE TITLE
[FEATURE REQ] Comprehensive updates for import_ids()

### ISSUE THREAD

**Issue by blarggy** [nflverse/nfl_data_py#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

import_ids() is really useful to map player IDs across various data sources, in particular I use this call to get a player ID csv table to map sleeper IDs to PFR usernames to scrape PFR pages for player information - unfortunately there are a lot of missing PFR IDs so I have to use a manual method to 'guess' the PFR tables for players that don't have a PFR ID in this .csv file. I'm not sure who the source is for this .csv file:

`
    # import data
    df = pandas.read_csv(r'https://raw.githubusercontent.com/dynastyprocess/data/master/files/db_playerids.csv')
`

### Describe the solution you'd like

It would be great to have this csv regularly updated with PFR IDs, I noticed Rookies are particularly bad, I know they just got added to PFR recently but perhaps there is a way to update this resource more regularly? 

### Describe alternatives you've considered

I suppose I could write a script that keeps my own database of known IDs that is checked separately of this table, but it would be convenient for others as well.

**Comment by alecglen** [comment]
@tanho63 do you manage this reference file?

**Comment by tanho63** [comment]
Specific issues can be filed at dynastyprocess/data, but I can’t really do much more than what is already automated in terms of join algorithms - would prefer missingness to false positives.

**Comment by alecglen** [comment]
Closing as there's no work to be done in nfl_data_py. @blarggy feel free to open an issue in https://github.com/dynastyprocess/data if you'd like to discuss it further.
